name: Rust CD Pipeline

on:
  workflow_call:
    secrets:
      EC2_USER:
        required: true
      EC2_KEY:
        required: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        shell: bash
        run: |
          echo "${{ secrets.EC2_KEY }}" > ~/RustSimpleServer.pem
          chmod 400 ~/RustSimpleServer.pem

      - name: Deploy Code
        shell: bash
        run: |
          # Copy relevant files to the EC2 instance
          scp -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem -r ./* ${{ secrets.EC2_USER }}@${{ env.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/RustSimpleServer

          # SSH into the EC2 instance and deploy
          ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ env.EC2_HOST }} "
            cd /home/${{ secrets.EC2_USER }}/RustSimpleServer &&
            docker-compose up --build -d
          "

