name: Rust CD Pipeline

on:
  workflow_call:
    secrets:
      EC2_USER:
        required: true
      EC2_KEY:
        required: true
      SERVICE_FILE:
        required: true
      TEST_VAR:
        required: true
    inputs:
      EC2_HOST:
        required: true
        type: string
        description: 'Public IP for EC2 instance'
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2

      - name: Install zig (for cross-compiling)
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: "0.15.2"

      - name: Download zigbuild
        shell: bash
        run: |
          cargo install --locked cargo-zigbuild

      - name: Add targets
        shell: bash
        run: |
          rustup target add aarch64-unknown-linux-musl

      - name: Build aarch64 binary
        shell: bash
        run: |
          cargo zigbuild --release --target aarch64-unknown-linux-musl

      - name: Set up SSH Key
        shell: bash
        run: |
          echo "${{ secrets.EC2_KEY }}" > ~/RustSimpleServer.pem
          chmod 400 ~/RustSimpleServer.pem

      - name: Set up directory
        shell: bash
        run: |
            ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }} 'mkdir -p /home/${{ secrets.EC2_USER }}/service'

      - name: Write env var shell script directly on target
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }} '
          cat > /home/${{ secrets.EC2_USER }}/service/set-env-var.sh <<'"'"'EOF'"'"'
          export BAR=${{ secrets.TEST_VAR }}
          EOF
          '

      - name: Stop the service
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }} "sudo systemctl stop web-server.service || true"

      - name: Push updated binary to target
        shell: bash
        run: |
          scp -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem -r target/aarch64-unknown-linux-musl/release/web_server ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/service/

      - name: Replace .service file
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }} '
          sudo bash -c "cat > /etc/systemd/system/web-server.service <<'"'"'EOF'"'"'
          "$(echo "${{ secrets.SERVICE_FILE }}" | base64 -d)"
          EOF
          "
          '

      - name: Start the service
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/RustSimpleServer.pem ${{ secrets.EC2_USER }}@${{ inputs.EC2_HOST }} "
          sudo systemctl daemon-reload &&
          sudo systemctl enable web-server.service &&
          sudo systemctl start web-server.service
          "

