name: Main
on:
  push:
    branches:
      - main
jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
  call-terraform:
    needs: call-ci
    uses: ./.github/workflows/terraform.yml
  call-cd:
    needs: call-terraform
    uses: ./.github/workflows/cd.yml

