name: Main
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
  call-terraform:
    needs: call-ci
    uses: ./.github/workflows/terraform.yml
  call-cd:
    needs: call-terraform
    uses: ./.github/workflows/cd.yml

